apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-db
spec:
  selector:
    matchLabels:
      appdb: testdb
  replicas: 1
  template:
    metadata:
      labels:
        appdb: testdb
    spec:
      containers:
      - name: test-db
        image: mongo:3.6
        env:
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "pythonapp-chart.fullname" . }}
              key: mongodb-db-name
        ports:
        - containerPort: 27017