apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pythonapp-chart.fullname" . }}
  labels:
    {{- include "pythonapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pythonapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pythonapp-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

